const CURRENCY_DICT = {
    // 常用主要貨幣
    "USD": { "zh": "美金", "en": "US Dollar" },
    "TWD": { "zh": "新台幣", "en": "New Taiwan Dollar" },
    "JPY": { "zh": "日圓", "en": "Japanese Yen" },
    "EUR": { "zh": "歐元", "en": "Euro" },
    "HKD": { "zh": "港幣", "en": "Hong Kong Dollar" },
    "KRW": { "zh": "韓元", "en": "South Korean Won" },
    "CNY": { "zh": "人民幣", "en": "Chinese Yuan" },
    "CNH": { "zh": "離岸人民幣", "en": "Chinese Yuan (Offshore)" },
    "GBP": { "zh": "英鎊", "en": "British Pound" },
    "AUD": { "zh": "澳幣", "en": "Australian Dollar" },
    "CAD": { "zh": "加幣", "en": "Canadian Dollar" },
    "SGD": { "zh": "新加坡幣", "en": "Singapore Dollar" },
    "CHF": { "zh": "瑞士法郎", "en": "Swiss Franc" },
    "NZD": { "zh": "紐西蘭幣", "en": "New Zealand Dollar" },

    // 亞洲其他地區
    "THB": { "zh": "泰銖", "en": "Thai Baht" },
    "MYR": { "zh": "馬來西亞幣", "en": "Malaysian Ringgit" },
    "VND": { "zh": "越南盾", "en": "Vietnamese Dong" },
    "PHP": { "zh": "菲律賓披索", "en": "Philippine Peso" },
    "IDR": { "zh": "印尼盾", "en": "Indonesian Rupiah" },
    "INR": { "zh": "印度盧比", "en": "Indian Rupee" },
    "MOP": { "zh": "澳門幣", "en": "Macanese Pataca" },
    "PKR": { "zh": "巴基斯坦盧比", "en": "Pakistani Rupee" },
    "BDT": { "zh": "孟加拉塔卡", "en": "Bangladeshi Taka" },
    "LKR": { "zh": "斯里蘭卡盧比", "en": "Sri Lankan Rupee" },
    "NPR": { "zh": "尼泊爾盧比", "en": "Nepalese Rupee" },
    "MVR": { "zh": "馬爾地夫盧比", "en": "Maldivian Rufiyaa" },
    "KHR": { "zh": "柬埔寨瑞爾", "en": "Cambodian Riel" },
    "LAK": { "zh": "寮國基普", "en": "Laotian Kip" },
    "MMK": { "zh": "緬甸元", "en": "Myanmar Kyat" },
    "BND": { "zh": "汶萊元", "en": "Brunei Dollar" },
    "MNT": { "zh": "蒙古圖格里克", "en": "Mongolian Tugrik" },
    "AFN": { "zh": "阿富汗尼", "en": "Afghan Afghani" },
    "BTN": { "zh": "不丹努爾特魯姆", "en": "Bhutanese Ngultrum" },

    // 中東地區
    "SAR": { "zh": "沙烏地里亞爾", "en": "Saudi Riyal" },
    "AED": { "zh": "阿聯酋迪拉姆", "en": "UAE Dirham" },
    "ILS": { "zh": "以色列新謝克爾", "en": "Israeli New Shekel" },
    "TRY": { "zh": "土耳其里拉", "en": "Turkish Lira" },
    "KWD": { "zh": "科威特第納爾", "en": "Kuwaiti Dinar" },
    "QAR": { "zh": "卡達里亞爾", "en": "Qatari Rial" },
    "BHD": { "zh": "巴林第納爾", "en": "Bahraini Dinar" },
    "OMR": { "zh": "阿曼里亞爾", "en": "Omani Rial" },
    "JOD": { "zh": "約旦第納爾", "en": "Jordanian Dinar" },
    "IRR": { "zh": "伊朗里亞爾", "en": "Iranian Rial" },
    "IQD": { "zh": "伊拉克第納爾", "en": "Iraqi Dinar" },
    "LBP": { "zh": "黎巴嫩鎊", "en": "Lebanese Pound" },
    "SYP": { "zh": "敘利亞鎊", "en": "Syrian Pound" },
    "YER": { "zh": "葉門里亞爾", "en": "Yemeni Rial" },

    // 美洲地區
    "BRL": { "zh": "巴西雷亞爾", "en": "Brazilian Real" },
    "MXN": { "zh": "墨西哥披索", "en": "Mexican Peso" },
    "ARS": { "zh": "阿根廷披索", "en": "Argentine Peso" },
    "CLP": { "zh": "智利披索", "en": "Chilean Peso" },
    "COP": { "zh": "哥倫比亞披索", "en": "Colombian Peso" },
    "PEN": { "zh": "秘魯索爾", "en": "Peruvian Sol" },
    "UYU": { "zh": "烏拉圭披索", "en": "Uruguayan Peso" },
    "BOB": { "zh": "玻利維亞諾", "en": "Bolivian Boliviano" },
    "PYG": { "zh": "巴拉圭瓜拉尼", "en": "Paraguayan Guarani" },
    "VES": { "zh": "委內瑞拉玻利瓦", "en": "Venezuelan Bolívar" },
    "PAB": { "zh": "巴拿馬巴波亞", "en": "Panamanian Balboa" },
    "CRC": { "zh": "哥斯大黎加科朗", "en": "Costa Rican Colón" },
    "DOP": { "zh": "多明尼加披索", "en": "Dominican Peso" },
    "CUP": { "zh": "古巴披索", "en": "Cuban Peso" },
    "GTQ": { "zh": "瓜地馬拉格查爾", "en": "Guatemalan Quetzal" },
    "HNL": { "zh": "宏都拉斯倫皮拉", "en": "Honduran Lempira" },
    "NIO": { "zh": "尼加拉瓜科多巴", "en": "Nicaraguan Córdoba" },
    "HTG": { "zh": "海地古德", "en": "Haitian Gourde" },
    "JMD": { "zh": "牙買加元", "en": "Jamaican Dollar" },
    "BBD": { "zh": "巴貝多元", "en": "Barbadian Dollar" },
    "BSD": { "zh": "巴哈馬元", "en": "Bahamian Dollar" },
    "BMD": { "zh": "百慕達元", "en": "Bermudian Dollar" },
    "BZD": { "zh": "貝里斯元", "en": "Belize Dollar" },
    "TTD": { "zh": "千里達及托巴哥元", "en": "Trinidad and Tobago Dollar" },
    "XCD": { "zh": "東加勒比元", "en": "East Caribbean Dollar" },
    "KYD": { "zh": "開曼群島元", "en": "Cayman Islands Dollar" },
    "GYD": { "zh": "蓋亞那元", "en": "Guyanaese Dollar" },
    "SRD": { "zh": "蘇利南元", "en": "Surinamese Dollar" },
    "AWG": { "zh": "阿魯巴弗羅林", "en": "Aruban Florin" },
    "ANG": { "zh": "荷屬安的列斯盾", "en": "Netherlands Antillean Guilder" },
    "XCG": { "zh": "加勒比海盾", "en": "Caribbean Guilder" },
    "CLF": { "zh": "智利發展單位", "en": "Chilean Unit of Account (UF)" },

    // 歐洲地區
    "RUB": { "zh": "俄羅斯盧布", "en": "Russian Ruble" },
    "UAH": { "zh": "烏克蘭格里夫納", "en": "Ukrainian Hryvnia" },
    "SEK": { "zh": "瑞典克朗", "en": "Swedish Krona" },
    "NOK": { "zh": "挪威克朗", "en": "Norwegian Krone" },
    "DKK": { "zh": "丹麥克朗", "en": "Danish Krone" },
    "PLN": { "zh": "波蘭茲羅提", "en": "Polish Zloty" },
    "HUF": { "zh": "匈牙利福林", "en": "Hungarian Forint" },
    "CZK": { "zh": "捷克克朗", "en": "Czech Koruna" },
    "RON": { "zh": "羅馬尼亞列伊", "en": "Romanian Leu" },
    "BGN": { "zh": "保加利亞列弗", "en": "Bulgarian Lev" },
    "RSD": { "zh": "塞爾維亞第納爾", "en": "Serbian Dinar" },
    "BAM": { "zh": "波黑可兌換馬克", "en": "Bosnia-Herzegovina Convertible Mark" },
    "HRK": { "zh": "克羅埃西亞庫納", "en": "Croatian Kuna" },
    "MKD": { "zh": "馬其頓代納爾", "en": "Macedonian Denar" },
    "ALL": { "zh": "阿爾巴尼亞列克", "en": "Albanian Lek" },
    "MDL": { "zh": "摩爾多瓦列伊", "en": "Moldovan Leu" },
    "BYN": { "zh": "白俄羅斯盧布", "en": "Belarusian Ruble" },
    "ISK": { "zh": "冰島克朗", "en": "Icelandic Króna" },
    "GEL": { "zh": "喬治亞拉里", "en": "Georgian Lari" },
    "AMD": { "zh": "亞美尼亞德拉姆", "en": "Armenian Dram" },
    "AZN": { "zh": "亞塞拜然馬納特", "en": "Azerbaijani Manat" },
    "GIP": { "zh": "直布羅陀鎊", "en": "Gibraltar Pound" },
    "IMP": { "zh": "曼島鎊", "en": "Isle of Man Pound" },
    "JEP": { "zh": "澤西鎊", "en": "Jersey Pound" },
    "GGP": { "zh": "根西鎊", "en": "Guernsey Pound" },
    "FOK": { "zh": "法羅群島克朗", "en": "Faroese Króna" },

    // 獨立國協及中亞
    "KZT": { "zh": "哈薩克堅戈", "en": "Kazakhstani Tenge" },
    "UZS": { "zh": "烏茲別克索姆", "en": "Uzbekistan Som" },
    "TMT": { "zh": "土庫曼馬納特", "en": "Turkmenistani Manat" },
    "TJS": { "zh": "塔吉克索莫尼", "en": "Tajikistani Somoni" },
    "KGS": { "zh": "吉爾吉斯索姆", "en": "Kyrgystani Som" },

    // 非洲地區
    "ZAR": { "zh": "南非蘭特", "en": "South African Rand" },
    "EGP": { "zh": "埃及鎊", "en": "Egyptian Pound" },
    "NGN": { "zh": "奈及利亞奈拉", "en": "Nigerian Naira" },
    "KES": { "zh": "肯亞先令", "en": "Kenyan Shilling" },
    "GHS": { "zh": "迦納塞地", "en": "Ghanaian Cedi" },
    "MAD": { "zh": "摩洛哥迪拉姆", "en": "Moroccan Dirham" },
    "DZD": { "zh": "阿爾及利亞第納爾", "en": "Algerian Dinar" },
    "TND": { "zh": "突尼西亞第納爾", "en": "Tunisian Dinar" },
    "XAF": { "zh": "中非金融合作法郎", "en": "CFA Franc BEAC" },
    "XOF": { "zh": "非洲金融共同體法郎", "en": "CFA Franc BCEAO" },
    "UGX": { "zh": "烏干達先令", "en": "Ugandan Shilling" },
    "TZS": { "zh": "坦尚尼亞先令", "en": "Tanzanian Shilling" },
    "AOA": { "zh": "安哥拉寬扎", "en": "Angolan Kwanza" },
    "MZN": { "zh": "莫三比克梅蒂卡爾", "en": "Mozambican Metical" },
    "ZMW": { "zh": "尚比亞克瓦查", "en": "Zambian Kwacha" },
    "ZWG": { "zh": "辛巴威金", "en": "Zimbabwean Gold" },
    "ZWL": { "zh": "辛巴威元", "en": "Zimbabwean Dollar" },
    "BWP": { "zh": "波札那普拉", "en": "Botswanan Pula" },
    "NAD": { "zh": "納米比亞元", "en": "Namibian Dollar" },
    "MUR": { "zh": "模里西斯盧比", "en": "Mauritian Rupee" },
    "MGA": { "zh": "馬達加斯加阿里亞里", "en": "Malagasy Ariary" },
    "ETB": { "zh": "衣索比亞比爾", "en": "Ethiopian Birr" },
    "SDG": { "zh": "蘇丹鎊", "en": "Sudanese Pound" },
    "SSP": { "zh": "南蘇丹鎊", "en": "South Sudanese Pound" },
    "LYD": { "zh": "利比亞第納爾", "en": "Libyan Dinar" },
    "CDF": { "zh": "剛果法郎", "en": "Congolese Franc" },
    "RWF": { "zh": "盧安達法郎", "en": "Rwandan Franc" },
    "BIF": { "zh": "蒲隆地法郎", "en": "Burundian Franc" },
    "GNF": { "zh": "幾內亞法郎", "en": "Guinean Franc" },
    "SLL": { "zh": "獅子山利昂", "en": "Sierra Leonean Leone" },
    "SLE": { "zh": "獅子山新利昂", "en": "Sierra Leonean Leone (New)" },
    "LRD": { "zh": "賴比瑞亞元", "en": "Liberian Dollar" },
    "GMD": { "zh": "甘比亞達拉西", "en": "Gambian Dalasi" },
    "CVE": { "zh": "維德角埃斯庫多", "en": "Cape Verdean Escudo" },
    "STN": { "zh": "聖多美普林西比多布拉", "en": "São Tomé and Príncipe Dobra" },
    "ERN": { "zh": "厄利垂亞納克法", "en": "Eritrean Nakfa" },
    "DJF": { "zh": "吉布地法郎", "en": "Djiboutian Franc" },
    "SOS": { "zh": "索馬利亞先令", "en": "Somali Shilling" },
    "KMF": { "zh": "葛摩法郎", "en": "Comorian Franc" },
    "MWK": { "zh": "馬拉威克瓦查", "en": "Malawian Kwacha" },
    "LSL": { "zh": "賴索托洛蒂", "en": "Lesotho Loti" },
    "SZL": { "zh": "史瓦帝尼里蘭吉尼", "en": "Swazi Lilangeni" },
    "SHP": { "zh": "聖赫勒拿鎊", "en": "Saint Helena Pound" },
    "MRU": { "zh": "茅利塔尼亞烏吉亞", "en": "Mauritanian Ouguiya" },

    // 大洋洲地區
    "FJD": { "zh": "斐濟元", "en": "Fijian Dollar" },
    "PGK": { "zh": "巴布亞紐幾內亞基那", "en": "Papua New Guinean Kina" },
    "SBD": { "zh": "索羅門群島元", "en": "Solomon Islands Dollar" },
    "VUV": { "zh": "萬那杜瓦圖", "en": "Vanuatu Vatu" },
    "WST": { "zh": "薩摩亞塔拉", "en": "Samoan Tala" },
    "TOP": { "zh": "東加潘加", "en": "Tongan Paʻanga" },
    "XPF": { "zh": "太平洋法郎", "en": "CFP Franc" },
    "KID": { "zh": "吉里巴斯元", "en": "Kiribati Dollar" },
    "TVD": { "zh": "吐瓦魯元", "en": "Tuvaluan Dollar" },
    "SCR": { "zh": "塞席爾盧比", "en": "Seychellois Rupee" },
    "FKP": { "zh": "福克蘭群島鎊", "en": "Falkland Islands Pound" },

    // 國際金融/組織
    "XDR": { "zh": "特別提款權", "en": "Special Drawing Rights" },

    // 主流加密貨幣 (來自 Fawazahmed API 列表)
    "btc": { "zh": "比特幣", "en": "Bitcoin" },
    "eth": { "zh": "以太坊", "en": "Ethereum" },
    "usdt": { "zh": "泰達幣", "en": "Tether" },
    "bnb": { "zh": "幣安幣", "en": "BNB" },
    "sol": { "zh": "索拉納", "en": "Solana" },
    "usdc": { "zh": "USD Coin", "en": "USDC" },
    "xrp": { "zh": "瑞波幣", "en": "XRP" },
    "doge": { "zh": "狗狗幣", "en": "Dogecoin" },
    "ada": { "zh": "艾達幣", "en": "Cardano" },
    "shib": { "zh": "柴犬幣", "en": "Shiba Inu" },
    "dot": { "zh": "波卡幣", "en": "Polkadot" },
    "ltc": { "zh": "萊特幣", "en": "Litecoin" },
    "matic": { "zh": "馬蹄幣 (Polygon)", "en": "Polygon" },
    "link": { "zh": "Chainlink", "en": "Chainlink" },
    "uni": { "zh": "Uniswap", "en": "Uniswap" },
    "avax": { "zh": "雪崩幣", "en": "Avalanche" },
    "trx": { "zh": "波場幣", "en": "TRON" },
    "atom": { "zh": "阿童木", "en": "Cosmos" }
};

function getCurrencyName(code, mode) {
    const data = CURRENCY_DICT[code] || { "zh": code, "en": code };
    switch (mode) {
        case 'zh': return data.zh;
        case 'en': return code;
        case 'both': return `${code} ${data.zh}`;
        default: return code;
    }
}